### ISSUE TITLE
MS-SQL Error in ACE Docker

### ISSUE THREAD

**Issue by paragkamra** [Invoke-IR/ACE#4]
HI,

i am facing this error when i am installing ACE Docker. 

in short i am getting error related to MS-SQL.

SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
    
Error: The evaluation period has expired.
This program has encountered a fatal error and cannot continue running.
The following diagnostic information is available:

       Reason: 0x00000001
       Signal: SIGSEGV - Segmentation fault (11)
   Stacktrace: 000056441d52fce7 00007fd80764b390 000056441d53ef52 
               000056441d5286db 000056441d527e59 
      Process: 6 - sqlservr
       Thread: 18 (application thread 0x1028)
  Instance Id: e623d85c-8194-4f4a-8c4e-fba2871e25e4
     Crash Id: 
  Build stamp: a37664e45e4156e76a53fa282fd694cb49f70c2037515f5684e3ce6dfa7549bc
/usr/src/ace/import-data.sh: line 4:     6 Aborted                 (core dumped) /opt/mssql/bin/sqlservr > /dev/null
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2749.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
    
  },

  "ConnectionStrings": {
Error: The evaluation period has expired.
This program has encountered a fatal error and cannot continue running.
The following diagnostic information is available:

       Reason: 0x00000001
       Signal: SIGSEGV - Segmentation fault (11)
   Stacktrace: 000056441d52fce7 00007fd80764b390 000056441d53ef52 
               000056441d5286db 000056441d527e59 
      Process: 6 - sqlservr
       Thread: 18 (application thread 0x1028)
  Instance Id: e623d85c-8194-4f4a-8c4e-fba2871e25e4
     Crash Id: 
  Build stamp: a37664e45e4156e76a53fa282fd694cb49f70c2037515f5684e3ce6dfa7549bc
/usr/src/ace/import-data.sh: line 4:     6 Aborted                 (core dumped) /opt/mssql/bin/sqlservr > /dev/null
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2749.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
    
  }
}

==========================================================

===============================================================
|        Thank you for provisioning ACE with Docker!!         |
|  Please use the following information to interact with ACE  |
===============================================================

  $settings = @{
    Uri        = 'https://192.168.28.131'
Error: The evaluation period has expired.
This program has encountered a fatal error and cannot continue running.
The following diagnostic information is available:

       Reason: 0x00000001
       Signal: SIGSEGV - Segmentation fault (11)
   Stacktrace: 000056441d52fce7 00007fd80764b390 000056441d53ef52 
               000056441d5286db 000056441d527e59 
      Process: 6 - sqlservr
       Thread: 18 (application thread 0x1028)
  Instance Id: e623d85c-8194-4f4a-8c4e-fba2871e25e4
     Crash Id: 
  Build stamp: a37664e45e4156e76a53fa282fd694cb49f70c2037515f5684e3ce6dfa7549bc
/usr/src/ace/import-data.sh: line 4:     6 Aborted                 (core dumped) /opt/mssql/bin/sqlservr > /dev/null
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2749.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible

PS: if i do netstat -antp for active connections and open ports i can see port number 1433 is open but when i do telnet or nc to check the connectivity it shows Connection Refused.

**Comment by jaredcatkinson** [comment]
This issue should be fixed with some of the commits I made tonight both here and on Docker Hub. Before today I was leaving the MSSQL_PID Environment Variable with its default value of “Development” which caused the container to only be valid for 90 days. You can now specify the MSSQL_PID value in the ace.env file. For more information on what this environment variable does, check out this site https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables.
